name: Run Tests

on:
  push:
    branches:
      - runTest

env:
  JSON: ${{ secrets.STORYBOOK_FILES_JSON }}
  PEM: ${{ secrets.STORYBOOK_FILES_PEM }}
      
jobs:
  build:
    name: Install Oracle and Run Tests
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download Make and Wget
      run: |
        choco install make
        choco install wget
    - name: Download Oracle Instant Client
      run: |
        pwd
        wget https://download.oracle.com/otn_software/nt/instantclient/213000/instantclient-basic-windows.x64-21.3.0.0.0.zip -q
        Expand-Archive -LiteralPath instantclient-basic-windows.x64-21.3.0.0.0.zip -DestinationPath .
        cd instantclient_21_3
        pwd
        $Env:oracle_dir = (pwd).path
        cd ..
    - name: Create oracle_dir.txt
      run: |
        echo $Env:oracle_dir > edu_storybook/core/data/oracle_dir.txt
    - name: Create StorybookFiles Files
      run: |
        echo $env:JSON > edu_storybook/core/data/StorybookFiles.json
        echo $env:PEM > edu_storybook/core/data/StorybookFiles.pem
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install Requirements
      run: |
        pip3 install -r requirements.txt
    - name: Run Tests
      run: |
        make test